add generate-endpoint-scan-pdf-report script
intezer/analyze-scripts pull request #7
Opened 2023-06-22 15:21 UTC by tzlilamar

2023-06-27 12:02 UTC, davidt99 requested changes

2023-06-27 12:02 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    hours = calc_scan_time.seconds // 3600
use `total_scononds()` instead

2023-06-27 12:02 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +        ep_analysis: Analysis,
rename to `endpoint_analysis`. Also the type hinting should be `EndpointAnalysis`

2023-06-27 12:02 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +                        sub_analysis.verdict in ("suspicious", "unknown")]
single quote

2023-06-27 12:02 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +        sub_analyses.sort(key=lambda value: value.verdict)
Not a must, but you want the suspicious to be first, and it works here only because suspicious is smaller lexicographically. You can change the sort in way that suspicious will be first regardless

2023-06-27 12:02 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +                for family in
it's better just to write as a regular for loop, it will make the code much clearer

2023-06-27 12:02 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    report_template_data = {"sub_analyses": sub_analyses,
single quote

2023-06-27 12:02 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    environment = jinja2.Environment()
add `autoescape=True` to make sure html won't be injected

2023-06-27 12:02 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    css_file_name = 'pdf-report.css'
rename to `endpoint_analysis_pdf_report.css`

2023-06-27 12:02 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    with open(css_file_name, mode="r", encoding="utf-8") as css_file:
single quote, no need for the utf-8

2023-06-27 12:02 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    parser = argparse.ArgumentParser(description="Generate a PDF and HTML reports for a given Intezer file scan")
single quote

2023-06-27 12:02 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    parser.add_argument("-s", "--analysisid", help="Endpoint Analysis IDs", required=True, nargs='+')
`--api-key`, it will translate to `api_key`

2023-06-27 12:02 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    parser.add_argument("-s", "--analysisid", help="Endpoint Analysis IDs", required=True, nargs='+')
same here. Also `-s` , change to `-a`

2023-06-27 12:02 UTC, davidt99 commented on iocs-extraction-to-csv/iocs_extraction_to_csv.py
> +    with open(filename, 'w', encoding="utf-8", errors="surrogateescape") as csvfile:
single quote

2023-06-27 12:02 UTC, davidt99 commented on iocs-extraction-to-csv/iocs_extraction_to_csv.py
> +        url = "https://analyze.intezer.com/analyses/" + analysis.analysis_id
there is a url in the result

2023-06-27 12:02 UTC, davidt99 commented on iocs-extraction-to-csv/iocs_extraction_to_csv.py
> +    filename = '../../../PycharmProjects/iocs_extraction/extracted_iocs.csv'  # Replace with your desired filename
Can we change this?

2023-06-27 13:32 UTC, tzlilamar commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    hours = calc_scan_time.seconds // 3600
it added .0 to the result so I left it with seconds, does that make a difference?

2023-06-27 13:33 UTC, tzlilamar commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    parser.add_argument("-s", "--analysisid", help="Endpoint Analysis IDs", required=True, nargs='+')
I could not understand what you mean by that

2023-06-27 14:03 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    hours = calc_scan_time.seconds // 3600
Yes, seconds represent the number of seconds on a particular day and not necessarily the total number of seconds. You can just surround the result in `int`

2023-06-28 07:40 UTC, davidt99 requested changes

2023-06-28 07:40 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    hours = int(calc_scan_time.total_seconds()) // 3600
Extract `calc_scan_time.total_seconds()` to a variable

2023-06-28 07:40 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +        if analysis.code_reuse is not None:
```suggestion
        if analysis.code_reuse:
```

2023-06-28 07:40 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    ep_analysis_metadata = endpoint_analysis.result()
rename to `endpoint_analysis_metadata`

2023-06-28 07:40 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    calc_scan_time = end_date - start_date
Rename to `scan_duration`

2023-06-28 07:40 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    ep_analysis_metadata['calc_scan_time'] = format_analysis_time(ep_analysis_metadata['scan_start_time'],
Rename here as well

2023-06-28 07:40 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    if ep_analysis_metadata['families'] is not None and len(ep_analysis_metadata['families']) > 0:
you can just check `ep_analysis_metadata['families']` - in python, empty list or dict are translated to false as well

2023-06-28 07:40 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +        if len(ep_analysis_metadata['families']) > 1:
No need for that, string.join doesn't add a comma if there is one item

2023-06-28 07:40 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +                            'ep_analysis_metadata': ep_analysis_metadata,
rename also here

2023-06-28 07:40 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    environment = jinja2.Environment()
We still need to add here the scaping

2023-06-28 07:40 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    parser.add_argument('-a', '--analysisid', help='Endpoint Analysis IDs', required=True, nargs='+')
change to `--analysis-id`

2023-06-28 07:40 UTC, davidt99 commented on iocs-extraction-to-csv/iocs_extraction_to_csv.py
> +        writer = csv.writer(csvfile)
Use `DictWriter` instead

2023-06-28 07:40 UTC, davidt99 commented on iocs-extraction-to-csv/iocs_extraction_to_csv.py
> +        url = analysis.result().get('analysis_url')
No need for the get, the `analysis_url` should always exist

2023-06-28 07:40 UTC, davidt99 commented on iocs-extraction-to-csv/iocs_extraction_to_csv.py
> +        if analysis.iocs['network']:
IOCs can be None here

2023-06-28 07:40 UTC, davidt99 commented on iocs-extraction-to-csv/iocs_extraction_to_csv.py
> +        if analysis.iocs['files']:
same

2023-06-28 07:40 UTC, davidt99 commented on iocs-extraction-to-csv/iocs_extraction_to_csv.py
> +    parser.add_argument('-k', '--apikey', help='Intezer API Key', required=True)
make the same change in the parameter names

2023-06-28 07:40 UTC, davidt99 commented on iocs-extraction-to-csv/iocs_extraction_to_csv.py
> +    parser.add_argument('-s', '--startdate', help='History start date, DD,MM,YYYY', required=True)
It's better to use ISO format: YYYY-MM-DD

2023-06-28 08:57 UTC, tzlilamar commented on iocs-extraction-to-csv/iocs_extraction_to_csv.py
> +        if analysis.iocs['network']:
right, but if they are None I don't want them in the list. can you please elaborate? I didn't understand

2023-06-28 09:13 UTC, davidt99 commented on iocs-extraction-to-csv/iocs_extraction_to_csv.py
> +        if analysis.iocs['network']:
If IOC will be None, the code will fail since it won't have 'network' info

2023-06-28 10:45 UTC, tzlilamar commented on generate-endpoint-scan-pdf-report/report_template.html
> +<style>{{css_input|safe}}</style>
@davidt99 see here |safe

2023-06-28 10:46 UTC, tzlilamar commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    environment = jinja2.Environment()
it looks like adding the |safe filtrer to the HTML CSS injection should prevent code injection https://jinja.palletsprojects.com/en/3.1.x/templates/#working-with-automatic-escaping

2023-06-28 12:12 UTC, davidt99 requested changes

2023-06-28 12:12 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    calc_scan_time = end_date - start_date
Rename this as well.

2023-06-28 12:12 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +def scan_duration(scan_start: str, scan_end: str):
add return value ` scan_duration(scan_start: str, scan_end: str) -> str:`

2023-06-28 12:12 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    endpoint_analysis_metadata['calc_scan_time'] = scan_duration(endpoint_analysis_metadata['scan_start_time'],
Rename here to scan_duration as well

2023-06-28 12:12 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +            endpoint_analysis_obj = EndpointAnalysis.from_analysis_id(endpoint_analysis_id)
Rename to `endpoint_analysis`

2023-06-28 12:12 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +def generate_reports(intezer_apikey, endpoint_analyses_ids):
Rename to api_key

2023-06-28 12:12 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    generate_reports('2ce26e8a-f658-4aa2-878e-9e2f2867bbfe', ['5e32dd43-19fd-407c-90b1-5393ec1fd05b',
Remove this

2023-06-28 12:12 UTC, davidt99 commented on iocs-extraction-to-csv/iocs_extraction_to_csv.py
> +            end_date = datetime.strptime(end_date_str, '%Y-%m-%d')
you have `datetime.from_isoformat()`

2023-06-28 12:50 UTC, davidt99 commented on generate-endpoint-scan-pdf-report/generate_ep_scan.py
> +    date_format = '%a, %d %b %Y %H:%M:%S %Z'
You can use `consts.DATE_FORMAT` from the sdk

2023-06-28 13:20 UTC, davidt99 approved these changes

2023-06-28 13:26 UTC, merged